### PR TITLE
Add copy of dorny/paths-filter@ca8fa4002 action

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

Because of security restrictions, public actions cannot be used directly
in ASF GitHub Action workflows. The options are either whitelisting the
action's repository + SHA or by creating a copy of the action or by
forking the original repository. GitHub Actions don't support git submodules, so
that is not an option. This commit creates a copy of the files
which is suitable for including the action in apache/pulsar-test-infra
repository.

This action can be referenced with
```
uses: apache/pulsar-test-infra/paths-filter@master
```

paths-filter action is needed by changes in https://github.com/apache/pulsar/pull/9963

### Modifications

Commands used to create the copy in pulsar-test-infra:
```
git clone --depth 1 https://github.com/dorny/paths-filter
cd paths-filter
git checkout ca8fa4002c226cbab8b50cc157d3f47899a49762
rm -rf .git .github
cd ..
git add paths-filter
```

### CODE REVIEW

**Comment by michaeljmarshall** [comment]
It looks like the source repository has had frequent updates/releases in the past 6 months. @lhotari, do you think we need to implement a process to ensure that our copy stays up to date? I'm not familiar with GitHub actions, so I'm not entirely sure what those releases included.

**Review by eolivelli — APPROVED** [review]

**Comment by eolivelli** [comment]
@michaeljmarshall in your opinion can we merge this patch in the current form in order to unblock apache/pulsar#9963 ?

**Review by michaeljmarshall — APPROVED** [review]
Approving to unblock the linked issue. I don't see any problem with using the action in the short term. I just wanted to call out a dependency that we'll need to maintain long term.

**Comment by lhotari** [comment]
> It looks like the source repository has had frequent updates/releases in the past 6 months. @lhotari, do you think we need to implement a process to ensure that our copy stays up to date? I'm not familiar with GitHub actions, so I'm not entirely sure what those releases included.

I guess we can sync on-demand if we run into issues with our use cases for paths-filter. The same commands I used to create the copy can be used to update the copy.

**Pull request merged**
