### PR TITLE
Add a github action for automatically cherry-pick PRs

### PR DESCRIPTION
**Pull request by zymap**
**Motivation**

We want to make the pulsar can cherry-pick automatically. This action will make a closed PR can cherry-pick by the command `/pulsarbot cherry-pick to branch-X.Y`.

When a PR is merged, the bot will say, 
```
Hey. If you want to cherry-pick this pr to a target branch, please comments '/pulsarbot, /pulsarbot cherry-pick to branch-X.Y'.
```
Then you can comment /pulsarbot cherry-pick to branch-X.Y, the bot will open a new PR for cherry-picking the closed PR.

If we open a new PR to do the cherry-pick, we can also use the CI to check the branch.

### CODE REVIEW

**Comment by sijie** [comment]
`/pulsarbot, please cherry-pick this pr to branch-X.Y` this phrase is too long. Can we use a phrase like `/pulsarbot cherry-pick to branch-X.Y`?

**Comment by zymap** [comment]
Yes, we can. I will update it.

**Comment by zymap** [comment]
@sijie I update the pulsar bot command. PTAL. Thanks.

**Comment by zymap** [comment]
@sijie  Please take a look when you have time.

**Comment by zymap** [comment]
ping @sijie

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
